apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mbwy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-mbwy@sha256:340c92fa7b3dc2c67fc09e165a2281024f942500a1ec6eb2037dceb0e57b9e90
        name: my-nodejs
        resources: {}
status: {}
